version: "3"
services:
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - "4444:4444"
  nexus_7.1.1:
    image: budtmo/docker-android-x86-7.1.1
    privileged: true
    depends_on:
      - selenium_hub
    volumes:
      - ./assets/spotify.apk:/opt/spotify.apk
      - ./video-nexus_7.1.1:/tmp/video
    ports:
      - "6080:6080"
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true