version: "3"
services:
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    container_name: Selenium_3.0
    ports:
      - "4545:4444"
  nexus_7.1.1:
    image: budtmo/docker-android-x86-7.1.1
    container_name: Nexus_7.1.1
    privileged: true
    depends_on:
      - selenium_hub
    volumes:
      - ./config/video-nexus_7.1.1:/tmp/video
    ports:
      - "6080:6080"
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true

  selenoid:
    network_mode: bridge
    container_name: Selenoid
    image: aerokube/selenoid
    volumes:
      - "./config:/etc/selenoid"
      #- "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/video:/opt/selenoid/video"
      - "./config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    container_name: Selenoid-UI
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
