version: "3"
services:
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - "4545:4444"
  nexus_7.1.1:
    image: budtmo/docker-android-x86-7.1.1
    container_name: Nexus_7.1.1
    privileged: true
    depends_on:
      - selenium_hub
    volumes:
      - ./output/videos:/tmp/video
    ports:
      - "6080:6080"
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true

  selenoid:
    container_name: Selenoid
    image: aerokube/selenoid:latest
    network_mode: bridge
    volumes:
      - ./config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./output/videos:/opt/selenoid/video
      - ./output/logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./output/videos

    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  android_7:
    image: "selenoid/android:7.0"
    container_name: Android
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid

  firefox:
    image: "selenoid/firefox"
    container_name: Firefox
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui

  Chrome:
    image: "selenoid/chrome"
    container_name: Chrome
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui
  Recorder:
    image: "selenoid/video-recorder"
    container_name: Recorder
    links:
      - selenoid
      - selenoid-ui
    depends_on:
      - selenoid
      - selenoid-ui